version: '3.8'
services:
  fastapi-app:
    image: mihaidobre1519/plant_project_api
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
  streamlit-app:
    image: mihaidobre1519/plant_project_streamlit
    ports:
      - "80:8501"
    environment:
      - API_URL=http://fastapi-app:8000/predict
