services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ../:/plant_village
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]